In [11]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [12]:
x.requires_grad_(True)
print(x.grad)

None


In [13]:
y = 2 * torch.dot(x,x)
y,y.shape

(tensor(28., grad_fn=<MulBackward0>), torch.Size([]))

In [14]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad.zero_()
y = x.sum()
y.backward()
y,x.grad

(tensor(6., grad_fn=<SumBackward0>), tensor([1., 1., 1., 1.]))

In [22]:
x.grad.zero_()
y = x * x
y.sum().backward()
y.sum(),x.grad

(tensor(14., grad_fn=<SumBackward0>), tensor([0., 2., 4., 6.]))

In [25]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
u,z,x.grad == u

(tensor([0., 1., 4., 9.]),
 tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>),
 tensor([True, True, True, True]))

In [26]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])