In [11]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [12]:
x.requires_grad_(True)
print(x.grad)

None


In [13]:
y = 2 * torch.dot(x,x)
y,y.shape

(tensor(28., grad_fn=<MulBackward0>), torch.Size([]))

In [14]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad.zero_()
y = x.sum()
y.backward()
y,x.grad

(tensor(6., grad_fn=<SumBackward0>), tensor([1., 1., 1., 1.]))

In [20]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad